---
- name: Install packages
  hosts: dev
  gather_facts: yes
  vars: 
    packages:
      - vim
      - tree
      - curl
      - wget
  tasks:
    - name: install packages with YUM
      yum:
        name: "{{ packages }}"
        
        state: latest
      when: ansible_pkg_mgr == "yum"
      register: results

    - name: Print Results
      debug:
        msg: "{{ results }}"

    - name: install packages with APT
      apt:
        name: "{{ packages }}"
          
        state: latest
      when: ansible_pkg_mgr == "apt" and results is failed


