---
- name: Update Packages
  hosts: dev
  gather_facts: yes
  tasks:
    - name: ping
      ping:

    - name: Update packages
      yum:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Update packages
      apt:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "apt"
      