---
- name: Copy file
  hosts: all
  gather_facts: yes
  tasks:
    - name: Copy
      copy:
        src:  /tmp/testing
        dest: /tmp/
      when: ansible_distribution == "CentOS" and
            ansible_distribution_major_version == "7"