---
- name: Call avriables
  hosts: all
  gather_facts: yes
  vars:
    - a: "hello"
    - b: "bye"
  tasks:
    - name: Print message
      debug:
        msg: "Python Version = {{ ansible_python_version }}"